Karen rodriguez tarea5
emolinaab/bootcamp-001 pull request #108
Opened 2022-09-14 01:50 UTC by krodriguezg57

2022-09-14 16:06 UTC, emolinaab requested changes
@krodriguezg57 , is not working

2022-09-14 16:57 UTC, krodriguezg57 commented
Hola @emolinaab, Acabo de revisar el trabajo nuevamente, pero en mi computador como a mis compañeros si funciona, quizás sea porque la forma en la que se mueve el puzzle es dandole click a la ficha que quiero mover y darle nuevamente click a donde la quiero mover, no sé entonces si así esté bien o debería ser de otra manera. 
Quedo atenta entonces al feedback para poder completar mi trabajo, muchas gracias.

2022-09-21 04:08 UTC, emolinaab commented
@krodriguezg57 oh ok it workked.

But when you click check the alert is showed several times.

2022-09-27 00:39 UTC, emolinaab approved these changes

2022-09-27 00:39 UTC, merged