Magazine-react-tarea-7
emolinaab/bootcamp-001 pull request #127
Opened 2022-09-19 15:29 UTC by ValentinaAtehortuaZ

2022-09-27 03:45 UTC, emolinaab requested changes

2022-09-27 03:45 UTC, emolinaab commented on Valentina-Atehortua-Zapata/tarea-7/magazine-react/src/components/Boxes.jsx
> +      <div className="box-left">
@ValentinaAtehortuaZ this should be a section

2022-09-27 03:45 UTC, emolinaab commented on Valentina-Atehortua-Zapata/tarea-7/magazine-react/src/components/Boxes.jsx
> +        <div className="text">
@ValentinaAtehortuaZ try to apply className="text" directly to h6 element

2022-09-27 03:45 UTC, emolinaab commented on Valentina-Atehortua-Zapata/tarea-7/magazine-react/src/components/Boxes.jsx
> +      <div className="container-boxes">
@ValentinaAtehortuaZ this should be a ul

2022-09-27 03:45 UTC, emolinaab commented on Valentina-Atehortua-Zapata/tarea-7/magazine-react/src/components/Boxes.jsx
> +        <div className="box">
@ValentinaAtehortuaZ all these boxes should be li elements

2022-09-27 03:45 UTC, emolinaab commented on Valentina-Atehortua-Zapata/tarea-7/magazine-react/src/components/Footer.jsx
> +    <div>
@ValentinaAtehortuaZ you should avoid the div element and use footer as root element

2022-11-15 17:26 UTC, ValentinaAtehortuaZ commented
Hello Esteban, I already made all the corrections.

2022-12-05 01:54 UTC, emolinaab approved these changes

2022-12-05 01:54 UTC, merged