Tarea 2 CSS - Jhon Esteban Correa - Con correcciones de tarea1
emolinaab/bootcamp-001 pull request #28
Opened 2022-08-24 20:27 UTC by Jhonec0814

2022-08-25 17:21 UTC, emolinaab requested changes
@Jhonec0814 , send the tarea-1 changes to tarea-1 branch and update the PR.

2022-08-25 17:21 UTC, emolinaab commented on jhon-esteban/tarea_2/html/index.html
> +                <div class="name">
@Jhonec0814   , this could be a section instead of a div

2022-08-25 17:21 UTC, emolinaab commented on jhon-esteban/tarea_2/html/index.html
> +                <div class="season">
@Jhonec0814 , this could be a section instead of a div

2022-08-26 17:05 UTC, Jhonec0814 commented
I have already pushed both branches mentioned above with the corrections.

2022-08-29 17:02 UTC, emolinaab approved these changes

2022-08-29 17:02 UTC, merged