David lectamo tarea 1
emolinaab/bootcamp-001 pull request #9
Opened 2022-08-22 21:58 UTC by L3C74M0

2022-08-23 14:17 UTC, emolinaab commented
@L3C74M0 , use react for this assignment is overkilling. Please use pure html and css

2022-08-23 16:05 UTC, L3C74M0 commented
Changed project to html and css

2022-08-26 15:35 UTC, emolinaab requested changes

2022-08-26 15:35 UTC, emolinaab commented on David-Lectamo/tarea-1/grid.css
> +.Ralfquestion {
@L3C74M0 , classes should be named using lowercase

2022-08-29 16:54 UTC, emolinaab approved these changes

2022-08-29 16:54 UTC, merged